### ISSUE TITLE
After Installing Alli-In-One Code Framework nothing happend

### ISSUE THREAD

**Issue by jascam** [jascam/CodePlexFoo#565]
Error in EventManager:
 
Name der fehlerhaften Anwendung: SampleBrowser.exe, Version: 1.0.0.0, Zeitstempel: 0x4fe84b64
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 6.1.7601.17651, Zeitstempel: 0x4e21213c
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000000cacd
ID des fehlerhaften Prozesses: 0x1550
Startzeit der fehlerhaften Anwendung: 0x01cd576e850885f9
Pfad der fehlerhaften Anwendung: C:\Users\Guido\AppData\Local\Apps\2.0\Y37EGDMV.LGV\HQ0RNK10.LK0\samp..tion_c3bce3770c238a49_0005.0002_c69a9d8cae29d8e9\SampleBrowser.exe
Pfad des fehlerhaften Moduls: C:\Windows\system32\KERNELBASE.dll
Berichtskennung: c2c6acf4-c361-11e1-9c51-20cf30704699
 

Windows 7/64Bit

#### Migrated CodePlex Work Item Details
CodePlex Work Item ID: '10953'
Vote count: '2'

**Comment by jascam** [comment]
I am getting the exact same error only i get it in norwegian.
I also found another message popping up with the first one in event manager:

Application: SampleBrowser.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException
Stack:
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.LoadComponent(System.Uri, Boolean)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.WrappedInvoke(System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.WrappedInvoke(System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.InvokeImpl(System.Windows.Threading.DispatcherOperation, System.Threading.CancellationToken, System.TimeSpan)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run()
   at SampleBrowser.App.Main()


This comment was posted by lego290 on 7/1/2012

**Comment by jascam** [comment]
Hello

Thanks for reporting the problem.  We are testing the application in Norwegian.  As soon as we reproduce the issue, I will update you again about the progress of fix.  

hi roadrunner64 
Would you mind telling me the language of your OS?

Thanks
Jialiang Ge

This comment was posted by Jialiang on 7/1/2012

**Comment by jascam** [comment]
Hi Jialiang,

my OS Language is German.

Best regards
roadrunner64

This comment was posted by roadrunner64 on 7/2/2012

**Comment by jascam** [comment]
Hello

The problem is fixed.  We have just released the fix.  Could you please reopen the sample browser to get the auto-update, and let me know if it works for you now?

Thanks
Jialiang Ge

This comment was posted by Jialiang on 7/2/2012

**Comment by jascam** [comment]
Hello,

i have tested it and it work's great
Thank's


This comment was posted by roadrunner64 on 7/11/2012

**Comment by jascam** [comment]
This comment was posted by  on 2/21/2013
